---
- hosts: windows
  name: This is a play within a playbook
  vars:
    iis_sites:
      - name: 'Ansible Playbook Test'
        port: '8080'
        path: 'C:\sites\playbooktest'
      - name: 'Ansible Playbook Test 2'
        port: '8081'
        path: 'C:\sites\playbooktest2'
    iis_test_message: "Hello World!  My test IIS Server"
  tasks:
  - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

  - name: Create site directory structure
      win_file:
        path: "{{ item.path }}"
        state: directory
    with_items: "{{ iis_sites }}"

  - name: Create IIS site
      win_iis_website:
        name: "{{ item.name }}"
        state: started
        port: "{{ item.port }}"
        physical_path: "{{ item.path }}"
    with_items: "{{ iis_sites }}"
    notify: restart iis service